// This file should be auto-generated by Supabase CLI
// Run: supabase gen types typescript --project-id your-project-ref > types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      studios: {
        Row: {
          id: string
          name: string
          email: string
          phone: string | null
          whatsapp_number: string
          storage_quota: number
          used_storage: number
          plan_tier: 'free' | 'basic' | 'pro' | 'enterprise'
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          email: string
          phone?: string | null
          whatsapp_number: string
          storage_quota?: number
          used_storage?: number
          plan_tier?: 'free' | 'basic' | 'pro' | 'enterprise'
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          phone?: string | null
          whatsapp_number?: string
          storage_quota?: number
          used_storage?: number
          plan_tier?: 'free' | 'basic' | 'pro' | 'enterprise'
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          studio_id: string
          project_name: string
          event_date: string
          event_type: 'wedding' | 'bar_mitzvah' | 'corporate' | 'birthday' | 'other'
          status: 'upcoming' | 'in_progress' | 'in_backup' | 'completed' | 'archived'
          folder_path: string
          total_size: number
          file_count: number
          photographer_name: string | null
          photographer_phone: string | null
          notes: string | null
          created_at: string
          updated_at: string
          moved_to_work_at: string | null
          completed_at: string | null
        }
        Insert: {
          id?: string
          studio_id: string
          project_name: string
          event_date: string
          event_type?: 'wedding' | 'bar_mitzvah' | 'corporate' | 'birthday' | 'other'
          status?: 'upcoming' | 'in_progress' | 'in_backup' | 'completed' | 'archived'
          folder_path: string
          total_size?: number
          file_count?: number
          photographer_name?: string | null
          photographer_phone?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          moved_to_work_at?: string | null
          completed_at?: string | null
        }
        Update: {
          id?: string
          studio_id?: string
          project_name?: string
          event_date?: string
          event_type?: 'wedding' | 'bar_mitzvah' | 'corporate' | 'birthday' | 'other'
          status?: 'upcoming' | 'in_progress' | 'in_backup' | 'completed' | 'archived'
          folder_path?: string
          total_size?: number
          file_count?: number
          photographer_name?: string | null
          photographer_phone?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          moved_to_work_at?: string | null
          completed_at?: string | null
        }
      }
      files: {
        Row: {
          id: string
          project_id: string
          file_name: string
          file_path: string
          file_size: number
          file_type: 'video' | 'image' | 'raw' | 'other'
          mime_type: string
          storage_tier: 'hot' | 'warm' | 'cold'
          cdn_url: string | null
          thumbnail_url: string | null
          duration_seconds: number | null
          width: number | null
          height: number | null
          uploaded_by: string | null
          uploaded_at: string
          last_accessed_at: string
        }
        Insert: {
          id?: string
          project_id: string
          file_name: string
          file_path: string
          file_size: number
          file_type: 'video' | 'image' | 'raw' | 'other'
          mime_type: string
          storage_tier?: 'hot' | 'warm' | 'cold'
          cdn_url?: string | null
          thumbnail_url?: string | null
          duration_seconds?: number | null
          width?: number | null
          height?: number | null
          uploaded_by?: string | null
          uploaded_at?: string
          last_accessed_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          file_name?: string
          file_path?: string
          file_size?: number
          file_type?: 'video' | 'image' | 'raw' | 'other'
          mime_type?: string
          storage_tier?: 'hot' | 'warm' | 'cold'
          cdn_url?: string | null
          thumbnail_url?: string | null
          duration_seconds?: number | null
          width?: number | null
          height?: number | null
          uploaded_by?: string | null
          uploaded_at?: string
          last_accessed_at?: string
        }
      }
      share_links: {
        Row: {
          id: string
          project_id: string
          token: string
          expires_at: string | null
          password_hash: string | null
          is_active: boolean
          max_downloads: number | null
          download_count: number
          access_count: number
          last_accessed_at: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          token?: string
          expires_at?: string | null
          password_hash?: string | null
          is_active?: boolean
          max_downloads?: number | null
          download_count?: number
          access_count?: number
          last_accessed_at?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          token?: string
          expires_at?: string | null
          password_hash?: string | null
          is_active?: boolean
          max_downloads?: number | null
          download_count?: number
          access_count?: number
          last_accessed_at?: string | null
          created_by?: string | null
          created_at?: string
        }
      }
      user_profiles: {
        Row: {
          id: string
          studio_id: string | null
          full_name: string | null
          role: 'owner' | 'admin' | 'member' | 'viewer'
          avatar_url: string | null
          phone: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          studio_id?: string | null
          full_name?: string | null
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          avatar_url?: string | null
          phone?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          studio_id?: string | null
          full_name?: string | null
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          avatar_url?: string | null
          phone?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
